language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh ;
    else
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh ;
    fi
  - bash miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - conda update --yes conda
  - conda config --add channels soft-matter
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy
  - source activate test-environment
  - pip install -r requirements.txt
  - pip install coveralls
  - echo $PATH
  - which python
  - conda info
  - conda list
  - python setup.py install

# command to run tests
script:
  - coverage run --source=pyproteome setup.py test

# command to notify coveralls
after_success:
  - coveralls
