version: Build {build}

skip_non_tags: true

build:
    verbosity: minimal

environment:
    matrix:
        - PYTHON_VERSION: 3.5
          MINICONDA: "C:\\Miniconda3"

install:
    - "SET PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "SET CONDA_PACKAGES=numpy scipy matplotlib pandas networkx scikit-learn seaborn biopython pyzmq"
    - "conda config --set always_yes yes --set changeps1 no"
    - "conda update conda"
    - "conda info -a"
    - "conda create -n env python=%PYTHON_VERSION% %CONDA_PACKAGES%"
    - "activate env"
    - "pip install -r requirements.txt jinja2==2.8.1" # Pin jinja for py < 3.6
    - "pip install pyinstaller"

build_script:
    - "pyinstaller pycamv.spec"

test_script:
    - "python setup.py test"

artifacts:
    - path: dist\PyCAMVerter.exe
      name: PyCAMVerter

deploy:
    - provider: GitHub
      description: ""
      artifact: PyCAMVerter
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: +GzJ//tQ7T8IYqT0tFSseDQ7N5+HfGrh6pv4DHVTMxy3fhd5KYYXUfhgXkqoCIfn
